### ISSUE TITLE
Capture issues

### ISSUE THREAD

**Issue by MattIPv4** [MagicCap/MagicCap#136]
# Desktop forcing
If you use either capture option and then abort with Escape, it forces all screens back to the macOS desktop, not whatever application they were in before.

# White flash
When you first enter either capture, it flashes all screens white, this really hurts your eyes...

Would be great if those could be fixed.

**Comment by codepupper** [comment]
The last thing happens to me as well and is really annoying when you're sitting in a dark room.


As for the first, I'm not sure what you mean. Do you mean that the current Fullscreen Window gets pushed to the front or that all minimised Apps in the Dock get pulled up?

**Comment by MattIPv4** [comment]
@codepupper Fullscreen (secondary desktop) applications, you get forced back to the primary desktop.

**Comment by codepupper** [comment]
https://yiff.design/i/rzeh.png

Like,,, when you're using Brave rn, then want to take a screenshot and it basically changes places with Discord?
Because that's a thing that happens to me

**Comment by MattIPv4** [comment]
@codepupper Jumps me all the way back to the desktop.

**Comment by codepupper** [comment]
huh, that's weird

**Comment by JakeMakesStuff** [comment]
This should be fixed in v1.1.0b1.
