### ISSUE TITLE
Config sidebar

### ISSUE THREAD

**Issue by MattIPv4** [MagicCap/MagicCap#142]
I believe that there should be some differentiation in the sidebar between the two capture options and everything else, as currently, it appears as though those two items will also be config modals, not triggering an actual capture.

Maybe put them at the top and then have a hr style break in the sidebar before all the modal menu items?

**Comment by JakeMakesStuff** [comment]
Fixed in https://github.com/MagicCap/MagicCap/commit/712339672b0773caff280387aec191b1740f48fe
