### ISSUE TITLE
Upload from clipboard

### ISSUE THREAD

**Issue by MattIPv4** [MagicCap/MagicCap#143]
It would be nice to have a keybind in place that takes the current image on the clipboard (assuming it is an image), and uploads it as if it were a screenshot taken by the software.

If further editing tools are added in future, it'd be even better if the keybind opened the editor with the image from the clipboard.

**Comment by JakeMakesStuff** [comment]
I'm not too good with understanding different types of clipboard storage. I'll try and figure this out on my own, but additional help might be needed.
