### ISSUE TITLE
View button

### ISSUE THREAD

**Issue by MattIPv4** [MagicCap/MagicCap#144]
If the app is configured to not save images locally, the view button should instead open the URL of the image, assuming there is one. Currently, the button does nothing if the image isn't saved locally.

Further, the button could open the URL whenever the image cannot be found locally, whether it is configured to be saved or not.

**Comment by JakeMakesStuff** [comment]
Added in https://github.com/MagicCap/MagicCap/commit/aab66e4b6ada0d7ac7bc561af491af3ee8484689
