### ISSUE TITLE
Pixel magnifier for selection

### ISSUE THREAD

**Issue by MattIPv4** [MagicCap/MagicCap#145]
Currently, the selection process is very much point and drag, which is great in most situations.

However, sometimes I like to get pixel perfect alignment on the edges of a screenshot, so it'd be great to have some form of pixel magnifier that could be toggled during the selection process :)

**Comment by JakeMakesStuff** [comment]
This is now complete.

**Comment by MattIPv4** [comment]
Resolved in https://github.com/MagicCap/MagicCap/commit/e844313c548c2e9fd1b2669f9be6490e9a873db9
