### ISSUE TITLE
General maintainability

### ISSUE THREAD

**Issue by MattIPv4** [MagicCap/MagicCap#148]
A key issue I have noticed with the current source for the software is that it is very hard to maintain.

To improve the maintainability of the program, I would request that all existing code and any future code is well commented to ensure that everyone can easily follow and understand what everything does.

Further, having dedicated docstrings for each method would help to improve the maintainability to make clear the intention and usage of all methods found within the code.

**Comment by JakeMakesStuff** [comment]
Yeah. To be honest, at the beginning MagicCap was just an automation tool for uploading screenshots from the screen capture tool on macOS. From there, it has grown an insane amount. I should look into modifying how the source code is structured.

**Comment by JakeMakesStuff** [comment]
I've been working on this recently, the code should be far more presentable now.

**Comment by MattIPv4** [comment]
@JakeMakesStuff Are you adding any eslint requirements for docstrings?

**Comment by JakeMakesStuff** [comment]
@MattIPv4 The require-jsdoc flag seems to be deprecated (https://eslint.org/docs/rules/require-jsdoc), shall we still use it?

**Comment by MattIPv4** [comment]
@JakeMakesStuff They never removed deprecated rules, and as they have no replacement rules, it might be what we're after. It'll be a lot of work to docstring everything that exists already.

I was more thinking that there isn't a specific need for docstrings describing what methods do fully, but comments throughout the code explaining what each block/line does.
