### ISSUE TITLE
Package size

### ISSUE THREAD

**Issue by MattIPv4** [MagicCap/MagicCap#149]
The distributed version of MagicCap for macOS (beta 1.1.0b3) is 441mb in size.
For comparrsion, Atom is 512mb in size.

I think we really need to work on making sure we distribute the smallest possible package to users!

**Comment by MattIPv4** [comment]
@JakeMakesStuff With ffmpeg dropped and the aws package reduced, is there anything more we can do?

**Comment by JakeMakesStuff** [comment]
Down to 297MB; I think that's as good as we are going to get it now to be honest.
