### ISSUE TITLE
Node 12 support

### ISSUE THREAD

**Issue by MattIPv4** [MagicCap/MagicCap#182]
Hello everyone!

As you may know, Python 2 is reaching EOL at the end of this year and is being dropped from future versions of macOS (after 10.15) as well as from many Linux distros.

We rely on Python 2 through the build dependency on node-gyp.
Node-gyp are working hard to bring in support for Python 3 but it has [been confirmed](https://github.com/nodejs/node/pull/28573#pullrequestreview-259080352) that will be landed on Node 12 but not 10.x or 8.x.

Therefore it is in our interests to move to Node 12.x from the current 10.x that we use.

**Comment by JakeMakesStuff** [comment]
Fixed in https://github.com/MagicCap/MagicCap/commit/4c1e42d3742c864c78b05920b0116af13c268587
