### ISSUE TITLE
is this error my fault?

### ISSUE THREAD

**Issue by TheTeaCup** [MagicCap/MagicCap#184]
<img width="423" alt="Screen Shot 2019-07-11 at 11 37 02 PM" src="https://user-images.githubusercontent.com/35646791/61100618-d0cf1e00-a434-11e9-904a-6001921d8458.png">

**Comment by TheTeaCup** [comment]
This the latest release for mac btw v2.0.0b3

**Comment by JakeMakesStuff** [comment]
No, it isn't your fault. Sorry, first-time initialization was something that I completely forgot to test after some large migrations. Your issue should be fixed in https://github.com/MagicCap/MagicCap/releases/tag/v2.0.0b4.

**Comment by JakeMakesStuff** [comment]
@TheTeaCup
