### ISSUE TITLE
Disable/Replace default Electron top area links

### ISSUE THREAD

**Issue by Chronomly** [MagicCap/MagicCap#198]
## Information
The links under the help section in the window are links to Electron's Help and Documentation

## Details
Unsure if the label of bug fits this or if feature suggestion would be better

### Description 
Help section links in preferences menu are all to Electron's website

### Steps to reproduce
Open Preferences from the indicator icon
Hover over Help
Click one of the links

### Expected behavior
Links to report an issue on GitHub or an invite to the support Discord group

### Screenshots
https://when-will.disilla.org/be/done/cq51f7M2bQb7.png

**Comment by MattIPv4** [comment]
Your image link isn't working fyi.

**Comment by Chronomly** [comment]
Works for me?

**Comment by MattIPv4** [comment]
Ah yeah, it's working now. Was getting a Cf error before.

Could you please provide the following info for me: `full output of `Preferences > About > Debug Information` in MagicCap`

**Comment by Chronomly** [comment]
Sure
```MagicCap Version: 2.0.2
System OS: Linux 5.3.6-200.fc30.x86_64 / Platform: linux
Installation ID: ba5b3ef8-9deb-4bec-9476-8cd2ec7b5341
Config: {"clipboard_action":2,"clipboard_hotkey":"Control+Delete","gif_hotkey":null,"hotkey":"Control+End","install_id":"ba5b3ef8-9deb-4bec-9476-8cd2ec7b5341","light_theme":false,"rlme_domain":"when-will.disilla.org/be/done","rlme_token":"TOKEN REDACTED","save_capture":true,"save_path":"/home/grey/Pictures/MagicCap/","sharex_sxcu_path":"/home/grey/Downloads/ratelimited.me_Random.sxcu","upload_capture":true,"uploader_type":"rlme"}```

**Comment by Chronomly** [comment]
This might fit better under feature suggestion

**Comment by MattIPv4** [comment]
Nah, this looks to be a bug. On macOS only the custom menu items we've defined show.
