### ISSUE TITLE
JSON parsing error when attempting to use SXCU files

### ISSUE THREAD

**Issue by Cairo2k18** [MagicCap/MagicCap#201]
## Information
```
MagicCap Version: 2.0.2
System OS: Linux 5.3.0-19-generic / Platform: linux
Installation ID: 3a31bfbd-3f12-4061-9163-be4833fbfd53
Config: {"clipboard_action":2,"clipboard_hotkey":null,"custom_body":{"domain":"love.is-rocket.science"},"custom_headers":{},"custom_image":"file","custom_url":"https://bisoga.xyz/api/upload/direct","gif_hotkey":null,"hotkey":"Insert","install_id":"3a31bfbd-3f12-4061-9163-be4833fbfd53","light_theme":false,"save_capture":true,"save_path":"/home/cairo2k18/Pictures/MagicCap/","sharex_sxcu_path":"/home/cairo2k18/filehost.sxcu","upload_capture":true,"uploader_type":"custom"}
```

### Description 
It does not let you use valid SXCU files and returns a JSON parsing error.

### Steps to reproduce
1. Open MagicCap Preferences
2. Open Uploader Settings
3. Click on the ShareX SXCU Custom Uploader Button
4. Input the exact path to the SXCU file
5. Test it, and see the parsing error be returned

### Expected behavior
I expected it to confirm that the custom uploader and SXCU file was valid and be able to use it as my default uploader.

### Screenshots
**Error Received:**
![](https://i.imgur.com/GB8RwPM.png)

**SXCU File Contents (obtained from bisoga.xyz):**
```json
﻿{
  "Name": "BiSoga File Host",
  "DestinationType": "ImageUploader, TextUploader, FileUploader",
  "RequestURL": "https://bisoga.xyz/api/upload/direct",
  "FileFormName": "file",
  "Arguments": {
    "domain": "i.biso.ga"
  }
}
```

**Comment by JakeMakesStuff** [comment]
This seems to work fine when I update the domain to a supported one as per your Discord, I assume it was just a bad file?
![upload](https://i.bi5.me/ReHulCfs.png)

**Comment by Cairo2k18** [comment]
> when I update the domain to a supported one as per your Discord

?? That made no sense to me?

**Comment by JakeMakesStuff** [comment]
I used the exact SXCU file specified with the domain changed as per the BiSoga discord. It worked.

**Comment by advaith1** [comment]
Interesting, looks like when downloading the file from https://static.bisoga.xyz/sharex/filehost.sxcu it says failed to parse, but after opening the file in TextEdit and saving it (without any edits), it then parses correctly. Maybe it's unable to parse the file saved on Windows for some reason?

(also the default domain has been updated)

**Comment by Cairo2k18** [comment]
> Interesting, looks like when downloading the file from https://static.bisoga.xyz/sharex/filehost.sxcu it says failed to parse, but after opening the file in TextEdit and saving it (without any edits), it then parses correctly. Maybe it's unable to parse the file saved on Windows for some reason?
> 
> (also the default domain has been updated)

Weird.. I did edit it in a text editor though to change the image url domain?

**Comment by JakeMakesStuff** [comment]
We’re the quotes different? macOS likes changing quotes to some odd Unicode value.
