### ISSUE TITLE
MagicCap local API

### ISSUE THREAD

**Issue by JakeMakesStuff** [MagicCap/MagicCap#53]
A local API for local applications (such as a Chrome extension) would be awesome. This could be a UNIX socket.

**Comment by theLMGN** [comment]
why not use a http/websocket api for it, whilst you do have to open an extra port, it's cross platform, and to prevent use by unintended apps, you could have a authentication system, where you have to get a code on the app, and insert that code into the app, and it'll get a auth token back through the api used to retrieve the code?

**Comment by JakeMakesStuff** [comment]
@theLMGN So I spoke to some people in the DMs a while back, and here's how I figured it'd go:
```
So the way it'll work is there'll be 3 token types:

- Global API token - This is the main token you'll be able to request from magiccap.me. This doesn't authorise you to immediately use endpoints on MagicCap instances, merely allowing you to request a one time request token.
- One time request token - There will be a API endpoint to make one of these. This will be given to the local MagicCap API via Websocket with {"type": "prompt", "one_time_token": "TOKEN_HERE"}. This will be used to prompt the user for permission. It will return a MagicCap local token if successful and can only be used once (you need to request another one after).
- MagicCap local token - Has full permission over MagicCap.```Btw it'd be a UNIX socket for a WebSocket if that makes sense.
