### ISSUE TITLE
Unable to compile for Void Linux

### ISSUE THREAD

**Issue by lnmds** [MagicCap/MagicCap#62]
I'm unable to run MagicCap's `linuxcompile` command on Void Linux x86_64.

Seems to be a hard depedency on `dpkg-deb` by `electron-packager`, which is for Ubuntu/Debian. If there isn't a need to support other Linux distributions, please signal so on the README, or create separate jobs for a "generalistic linux build"

**Comment by JakeMakesStuff** [comment]
Sorry, I wasn't aware that *.deb packaging on some Linux distros was a problem. I'll look into that.
