### ISSUE TITLE
File Configuration does not function

### ISSUE THREAD

**Issue by aerofusionyt** [MagicCap/MagicCap#80]
**Issue**
The 'File Configuration' option does not work and resets back to the default after an app restart.

**OS & Config**
macOS 10.12.6 Sierra (16G29)
MagicCap v0.6.3
File saving is **ON**.
This happens **whether or not** MagicCap is set to upload or copy to clipboard.

**Reproduction**
1) Change the file directory to any folder other than the default MagicCap folder.
2) Take a screenshot of anything. If this reproduces correctly, it either **will not save** or will still **save to the MagicCap** directory.
3) Restart the app after setting your custom folder. The directory will have reset to MagicCap.

**Notes**
I cannot test this on Linux or on Windows at the moment. This may just be a macOS bug.

**Comment by JakeMakesStuff** [comment]
@aerofusionyt 

My bad, that appears like a oversight on my part after migrating to vue.js. It will be fixed next release!

**Comment by JakeMakesStuff** [comment]
Also I try and keep personal drama away from this project, but I didn't realise disagreeing with a point of view was block worthy in 2019. Anyway, if you want to speak about that DM me somewhere:

![image](https://user-images.githubusercontent.com/23243233/51790309-4008cc80-218b-11e9-915d-9159f2f52104.png)

**Comment by JakeMakesStuff** [comment]
^ is sorted now too.

**Comment by aerofusionyt** [comment]
No clue why I had you blocked haha, whoops.
Also a bit of an unrelated typo - 
![image](https://user-images.githubusercontent.com/29132033/51790785-95cb7d80-2167-11e9-80fe-84a7f885df5e.png)

repersent should be represent. Not a big deal but a very quick fix.
